<?php
namespace Civi\Api4;

/**
 * ShareNode entity.
 *
 * Provided by the CiviShare extension.
 *
 * @package Civi\Api4
 */
class ShareNode extends Generic\DAOEntity {
  public static function create($checkPermissions = TRUE)
  {
    return parent::create($checkPermissions); // TODO: Change the autogenerated stub
  }
}
